version: '3.8'

services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to api:3000/orders/stripe_webhook"
    env_file:
      - .env.docker
  db:
    image: 'postgres:latest'
    restart: always
    container_name: system-design-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: system-design-cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  api-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-1
    restart: unless-stopped
    stdin_open: true
    env_file:
      - ./.env.docker
    tty: true
    depends_on:
      - db
      - stripe-cli
      - cache
  api-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-2
    restart: unless-stopped
    stdin_open: true
    env_file:
      - ./.env.docker
    tty: true
    depends_on:
      - db
      - stripe-cli
      - cache
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - api-1
      - api-2
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db:
    driver: local
  cache:
    driver: local